import re
import os
import time
import regex
import emoji
import pandas as pd
import numpy as np
import preprocessor as p


resource_dir = '/home/ed/github/pod_tweets/resources/'
tweets_dir = '/home/ed/github/pod_tweets/follower_twts/'

p.set_options(p.OPT.URL, p.OPT.MENTION, p.OPT.HASHTAG, p.OPT.EMOJI)
punct_str = '''!"$%&'()*+,-./:;<=>?[\]^_`{|}~’'''

stop_words = [# 'ad',
    'am',
    'an',
    'as',
    'at',
    'be',
    'by',
    # 'dc',
    'de',
    'do',
    # 'dr',
    'el',
    'en',
    'go',
    'he',
    'hi',
    'id',
    'if',
    'im',
    'in',
    'is',
    'it',
    'la',
    'me',
    # 'mr',
    'my',
    'no',
    'of',
    'oh',
    'ok',
    'on',
    'or',
    'pm',
    'rt',
    'so',
    'st',
    'to',
    # 'tv',
    'up',
    'us',
    # 'vs',
    'we',
    'ya',
    '1st',
    # 'act',
    # 'age',
    # 'ago',
    # 'air',
    'all',
    'amp',
    'and',
    'any',
    # 'app',
    'are',
    # 'art',
    'ask',
    # 'ass',
    # 'bad',
    'big',
    'bit',
    'boy',
    'but',
    'buy',
    'can',
    'car',
    'dad',
    'day',
    'did',
    'die',
    'dog',
    'due',
    'end',
    'etc',
    # 'fan',
    'far',
    'few',
    'for',
    # 'fox',
    # 'fun',
    'get',
    # 'god',
    # 'gop',
    'got',
    # 'gun',
    'guy',
    'had',
    'has',
    'her',
    'hes',
    'hey',
    'him',
    'his',
    # 'hit',
    'how',
    'ill',
    'its',
    'ive',
    'jim',
    'job',
    'joe',
    # 'key',
    # 'kid',
    'law',
    'let',
    'lie',
    'lol',
    'lot',
    'low',
    'man',
    'map',
    'may',
    # 'men',
    'met',
    # 'mom',
    # 'new',
    # 'nfl',
    'not',
    'now',
    'off',
    # 'old',
    'omg',
    'one',
    'our',
    'out',
    'own',
    # 'pay',
    'put',
    'que',
    'red',
    'run',
    # 'sad',
    'saw',
    'say',
    'see',
    'set',
    'she',
    'sir',
    # 'son',
    # 'tax',
    'the',
    'too',
    'top',
    'try',
    'two',
    'use',
    'via',
    # 'war',
    'was',
    'way',
    'who',
    'why',
    # 'win',
    # 'won',
    'wow',
    'yes',
    'yet',
    'you',
    # '2020',
    # 'able',
    # 'also',
    # 'away',
    # 'baby',
    # 'back',
    # 'beat',
    # 'been',
    # 'best',
    # 'bill',
    # 'blue',
    # 'book',
    # 'born',
    # 'both',
    # 'bowl',
    # 'call',
    # 'came',
    # 'cant',
    # 'care',
    # 'case',
    # 'city',
    # 'code',
    # 'cold',
    # 'come',
    # 'cool',
    # 'cost',
    'damn',
    # 'data',
    # 'date',
    # 'days',
    # 'dead',
    # 'deal',
    # 'dear',
    # 'dems',
    # 'died',
    # 'does',
    # 'done',
    # 'dont',
    # 'down',
    # 'each',
    # 'easy',
    # 'else',
    # 'even',
    # 'ever',
    # 'face',
    # 'fact',
    # 'fair',
    # 'fake',
    # 'fall',
    # 'fans',
    # 'fear',
    # 'feel',
    # 'film',
    # 'find',
    # 'fire',
    # 'food',
    # 'four',
    # 'free',
    # 'from',
    'fuck',
    # 'full',
    # 'game',
    # 'gave',
    # 'gets',
    # 'gift',
    # 'girl',
    # 'give',
    # 'glad',
    # 'goes',
    # 'good',
    # 'guys',
    # 'half',
    # 'hand',
    # 'hard',
    # 'hate',
    'have',
    # 'head',
    # 'hear',
    # 'hell',
    # 'help',
    # 'here',
    # 'high',
    # 'hold',
    # 'home',
    # 'hope',
    # 'hour',
    # 'huge',
    # 'idea',
    # 'info',
    # 'into',
    # 'iowa',
    # 'iran',
    # 'isnt',
    # 'jobs',
    # 'john',
    # 'join',
    # 'just',
    # 'keep',
    # 'kids',
    # 'kind',
    # 'king',
    # 'knew',
    # 'know',
    # 'kobe',
    # 'lack',
    # 'last',
    # 'late',
    # 'lead',
    # 'left',
    # 'less',
    # 'lets',
    # 'lies',
    # 'life',
    # 'line',
    # 'link',
    # 'list',
    # 'live',
    # 'long',
    # 'look',
    # 'lose',
    # 'lost',
    # 'lots',
    # 'love',
    # 'luck',
    # 'made',
    # 'make',
    # 'many',
    # 'mean',
    # 'meet',
    # 'mike',
    # 'mind',
    # 'miss',
    # 'more',
    # 'most',
    # 'move',
    # 'much',
    # 'must',
    # 'name',
    # 'near',
    # 'need',
    # 'news',
    # 'next',
    # 'nice',
    # 'okay',
    # 'once',
    # 'ones',
    # 'only',
    # 'open',
    # 'over',
    # 'paid',
    # 'park',
    # 'part',
    # 'pass',
    # 'past',
    # 'pete',
    # 'pick',
    # 'plan',
    # 'play',
    # 'poor',
    # 'post',
    # 'race',
    # 'read',
    # 'real',
    # 'rest',
    # 'room',
    # 'rule',
    # 'rush',
    # 'safe',
    # 'said',
    # 'same',
    # 'save',
    # 'says',
    # 'seem',
    # 'seen',
    # 'send',
    # 'sent',
    # 'shes',
    # 'shit',
    # 'shot',
    # 'show',
    # 'sick',
    # 'side',
    # 'sign',
    # 'some',
    # 'song',
    # 'soon',
    # 'star',
    # 'stay',
    # 'step',
    # 'stop',
    # 'such',
    # 'sure',
    # 'take',
    # 'talk',
    # 'team',
    # 'tell',
    # 'than',
    # 'that',
    # 'them',
    # 'then',
    # 'they',
    # 'time',
    # 'told',
    # 'took',
    # 'true',
    # 'turn',
    # 'used',
    # 'very',
    # 'vote',
    # 'wait',
    # 'want',
    # 'ways',
    # 'week',
    # 'well',
    # 'went',
    # 'were',
    # 'weve',
    # 'what',
    # 'when',
    # 'whos',
    # 'wife',
    # 'will',
    # 'wins',
    # 'wish',
    # 'with',
    # 'wont',
    # 'word',
    # 'work',
    # 'yall',
    # 'yeah',
    # 'year',
    # 'york',
    'your',
    # 'about',
    # 'after',
    # 'again',
    # 'agree',
    # 'allow',
    # 'alone',
    # 'along',
    # 'among',
    # 'apply',
    # 'arent',
    # 'asked',
    # 'based',
    # 'being',
    # 'biden',
    # 'black',
    # 'board',
    # 'books',
    # 'brain',
    # 'break',
    # 'bring',
    # 'build',
    # 'calls',
    # 'cause',
    # 'check',
    # 'child',
    # 'china',
    # 'class',
    # 'clear',
    # 'close',
    # 'comes',
    # 'could',
    # 'court',
    # 'cover',
    # 'crazy',
    # 'daily',
    # 'death',
    # 'didnt',
    # 'doing',
    # 'early',
    # 'email',
    # 'enjoy',
    # 'event',
    # 'every',
    # 'facts',
    # 'field',
    # 'fight',
    # 'final',
    # 'first',
    # 'folks',
    # 'force',
    # 'found',
    # 'front',
    # 'funny',
    # 'games',
    # 'girls',
    # 'given',
    # 'going',
    # 'gonna',
    # 'great',
    # 'green',
    # 'group',
    # 'guess',
    # 'hands',
    # 'happy',
    # 'heard',
    # 'heart',
    # 'hello',
    # 'heres',
    # 'honor',
    # 'hours',
    # 'house',
    # 'human',
    # 'idiot',
    # 'issue',
    # 'jesus',
    # 'knows',
    # 'later',
    # 'learn',
    # 'least',
    # 'leave',
    # 'legal',
    # 'level',
    # 'light',
    # 'lives',
    # 'local',
    # 'looks',
    # 'loved',
    # 'makes',
    # 'march',
    # 'maybe',
    # 'means',
    # 'media',
    # 'might',
    # 'mitch',
    # 'money',
    # 'month',
    # 'moved',
    # 'movie',
    # 'music',
    # 'needs',
    # 'never',
    # 'night',
    # 'obama',
    # 'often',
    # 'order',
    # 'other',
    # 'party',
    # 'peace',
    # 'phone',
    # 'photo',
    # 'piece',
    # 'place',
    # 'point',
    # 'power',
    # 'press',
    # 'proud',
    # 'radio',
    # 'reach',
    # 'ready',
    # 'right',
    # 'rules',
    # 'seems',
    # 'sense',
    # 'shame',
    # 'share',
    # 'short',
    # 'shows',
    # 'since',
    # 'small',
    # 'sorry',
    # 'south',
    # 'space',
    # 'speak',
    # 'spend',
    # 'spent',
    # 'staff',
    # 'stage',
    # 'stand',
    # 'start',
    # 'state',
    # 'still',
    # 'story',
    # 'stuff',
    # 'super',
    # 'takes',
    # 'texas',
    # 'thank',
    'thats',
    'their',
    'there',
    'these',
    'thing',
    'think',
    'those',
    # 'three',
    # 'times',
    # 'tired',
    # 'today',
    # 'trial',
    # 'tried',
    # 'truly',
    # 'trump',
    # 'truth',
    # 'tweet',
    'u200d',
    # 'under',
    # 'union',
    # 'until',
    # 'using',
    # 'video',
    # 'views',
    # 'visit',
    # 'voice',
    # 'voted',
    # 'voter',
    # 'votes',
    # 'wants',
    # 'wasnt',
    # 'watch',
    # 'water',
    # 'weeks',
    # 'weird',
    'whats',
    'where',
    'which',
    'while',
    # 'white',
    # 'whole',
    # 'woman',
    # 'women',
    # 'words',
    # 'works',
    # 'world',
    # 'worst',
    # 'worth',
    # 'would',
    # 'write',
    # 'wrong',
    # 'wrote',
    # 'years',
    'youll',
    # 'young',
    'youre',
    'yours',
    'youve',
    # 'access',
    # 'across',
    # 'action',
    # 'almost',
    # 'always',
    # 'answer',
    # 'anthem',
    # 'anyone',
    # 'around',
    # 'asking',
    # 'attack',
    # 'become',
    # 'before',
    # 'behind',
    # 'bernie',
    # 'better',
    # 'beyond',
    # 'bolton',
    # 'bryant',
    # 'called',
    # 'cancer',
    # 'cannot',
    # 'career',
    # 'caucus',
    # 'center',
    # 'chance',
    # 'change',
    # 'chiefs',
    # 'choice',
    # 'choose',
    # 'church',
    # 'coming',
    # 'county',
    # 'course',
    # 'create',
    # 'crisis',
    # 'debate',
    # 'doesnt',
    # 'donald',
    # 'donate',
    # 'during',
    # 'either',
    # 'energy',
    # 'enough',
    # 'entire',
    # 'expect',
    # 'failed',
    # 'family',
    # 'follow',
    # 'forget',
    # 'former',
    # 'friday',
    # 'friend',
    # 'future',
    # 'giving',
    # 'global',
    # 'google',
    # 'happen',
    # 'havent',
    # 'having',
    # 'health',
    # 'impact',
    # 'issues',
    # 'joined',
    # 'kansas',
    # 'killed',
    # 'latest',
    # 'leader',
    # 'likely',
    # 'listen',
    # 'little',
    # 'living',
    # 'longer',
    # 'making',
    # 'matter',
    # 'member',
    # 'middle',
    # 'missed',
    # 'moment',
    # 'monday',
    # 'months',
    # 'myself',
    # 'nation',
    # 'needed',
    # 'number',
    # 'office',
    # 'online',
    # 'others',
    # 'paying',
    # 'people',
    # 'person',
    # 'please',
    # 'points',
    # 'police',
    # 'policy',
    # 'pretty',
    # 'prison',
    # 'public',
    # 'racism',
    # 'racist',
    # 'rather',
    # 'really',
    # 'reason',
    # 'record',
    # 'remove',
    # 'report',
    # 'review',
    # 'rights',
    # 'russia',
    # 'saying',
    # 'school',
    # 'season',
    # 'second',
    # 'seeing',
    # 'senate',
    # 'series',
    # 'sexual',
    # 'should',
    # 'single',
    # 'social',
    # 'sounds',
    # 'speech',
    # 'sports',
    # 'spread',
    # 'states',
    # 'street',
    # 'strong',
    # 'stupid',
    # 'sunday',
    # 'system',
    # 'taking',
    # 'thanks',
    'theres',
    'theyre',
    # 'things',
    # 'thinks',
    # 'though',
    # 'thread',
    # 'todays',
    # 'trumps',
    # 'trying',
    # 'tweets',
    # 'united',
    # 'update',
    # 'voters',
    # 'voting',
    # 'wanted',
    # 'warren',
    # 'wonder',
    # 'worked',
    # 'account',
    # 'address',
    # 'against',
    # 'already',
    # 'amazing',
    # 'america',
    # 'another',
    # 'article',
    # 'awesome',
    # 'because',
    # 'believe',
    # 'between',
    # 'biggest',
    # 'billion',
    # 'brought',
    # 'calling',
    # 'changed',
    # 'climate',
    # 'clinton',
    # 'college',
    # 'comment',
    # 'company',
    # 'content',
    # 'control',
    # 'couldnt',
    # 'country',
    # 'culture',
    # 'current',
    # 'defense',
    # 'deserve',
    # 'elected',
    # 'episode',
    # 'exactly',
    # 'excited',
    # 'federal',
    # 'feeling',
    # 'finally',
    # 'florida',
    # 'foreign',
    # 'forever',
    # 'forward',
    # 'friends',
    # 'fucking',
    # 'general',
    # 'getting',
    # 'happens',
    # 'hearing',
    # 'hillary',
    # 'himself',
    # 'history',
    # 'imagine',
    # 'instead',
    # 'january',
    # 'justice',
    # 'leaders',
    # 'looking',
    # 'matters',
    # 'medical',
    # 'meeting',
    # 'members',
    # 'message',
    # 'michael',
    # 'million',
    # 'minutes',
    # 'morning',
    # 'nothing',
    # 'opinion',
    # 'outside',
    # 'parents',
    # 'perfect',
    # 'picture',
    # 'playing',
    # 'podcast',
    # 'primary',
    # 'problem',
    # 'process',
    # 'program',
    # 'project',
    # 'protect',
    # 'putting',
    # 'reading',
    # 'realize',
    # 'respect',
    # 'results',
    # 'retweet',
    # 'running',
    # 'sanders',
    # 'schools',
    # 'science',
    # 'senator',
    # 'serious',
    # 'service',
    # 'sharing',
    # 'showing',
    # 'sitting',
    # 'someone',
    # 'special',
    # 'started',
    # 'stories',
    # 'student',
    # 'support',
    # 'talking',
    # 'telling',
    # 'thought',
    # 'through',
    # 'tonight',
    # 'totally',
    # 'tuesday',
    # 'twitter',
    # 'ukraine',
    # 'waiting',
    # 'watched',
    # 'weekend',
    # 'welcome',
    # 'whether',
    # 'winning',
    # 'without',
    # 'workers',
    # 'working',
    # 'wouldnt',
    # 'writing',
    # 'actually',
    # 'american',
    # 'anything',
    # 'argument',
    # 'behavior',
    # 'birthday',
    # 'breaking',
    # 'building',
    # 'business',
    # 'campaign',
    # 'caucuses',
    # 'children',
    # 'congrats',
    # 'congress',
    # 'continue',
    # 'criminal',
    # 'daughter',
    # 'decision',
    # 'democrat',
    # 'election',
    # 'everyone',
    # 'evidence',
    # 'families',
    # 'favorite',
    # 'fighting',
    # 'football',
    # 'halftime',
    # 'happened',
    # 'interest',
    # 'language',
    # 'learning',
    # 'majority',
    # 'military',
    # 'millions',
    # 'missouri',
    # 'national',
    # 'november',
    # 'official',
    # 'personal',
    # 'politics',
    # 'possible',
    # 'powerful',
    # 'probably',
    # 'question',
    # 'remember',
    # 'reminder',
    # 'research',
    # 'response',
    # 'saturday',
    # 'security',
    # 'senators',
    # 'shouldnt',
    # 'starting',
    # 'students',
    # 'thinking',
    # 'thoughts',
    # 'together',
    # 'tomorrow',
    # 'training',
    # 'violence',
    # 'virginia',
    # 'watching',
    # 'whatever',
    # 'yourself',
    # 'americans',
    # 'attention',
    # 'available',
    # 'beautiful',
    # 'bloomberg',
    # 'candidate',
    # 'celebrate',
    # 'christmas',
    # 'community',
    # 'democracy',
    # 'democrats',
    # 'different',
    # 'documents',
    # 'education',
    # 'following',
    # 'happening',
    # 'impeached',
    # 'important',
    # 'including',
    # 'interview',
    # 'listening',
    # 'literally',
    # 'mcconnell',
    # 'political',
    # 'president',
    # 'questions',
    # 'seriously',
    # 'something',
    # 'sometimes',
    # 'statement',
    # 'witnesses',
    # 'wonderful',
    # 'yesterday',
    # 'absolutely',
    # 'candidates',
    # 'commercial',
    # 'completely',
    # 'conference',
    # 'corruption',
    # 'definitely',
    # 'difference',
    # 'democratic',
    'especially',
    # 'everything',
    # 'experience',
    # 'government',
    # 'healthcare',
    # 'incredible',
    # 'leadership',
    # 'presidents',
    # 'republican',
    # 'supporters',
    # 'supporting',
    'themselves',
    'u2066u2069',
    # 'understand',
    # 'university',
    # 'washington',
    # 'communities',
    # 'coronavirus',
    # 'immigration',
    # 'impeachment',
    # 'information',
    # 'interesting',
    # 'opportunity',
    # 'republicans',
    # 'constitution',
    # 'conversation',
    # 'presidential',
    # 'administration',
    # 'congratulations'
]

def find_emoji(text):
    '''
    '''
    emoji_list = []
    data = regex.findall(r'\X', text)
    for word in data:
        if any(char in emoji.UNICODE_EMOJI for char in word):
            emoji_list.append(word)

    return emoji_list


def find_hash(text):
    '''
    '''
    hashtag_list = []
    data = regex.findall(r'#\w*', text)
    for word in data:
        hashtag_list.append(word)
    return hashtag_list


def find_mention(text):
    '''
    '''
    mention_list = []
    data = regex.findall(r'@\w*', text)
    for word in data:
        mention_list.append(word)
    return mention_list


def tweet_split_2_process(user_id, tweets_str):
    '''
    '''
    df_out = pd.DataFrame(columns=['user_id'], dtype=np.int32)
    output_txt = ''
    output_emoji = ''
    output_hash = ''
    output_mention = ''

    tweets_str = tweets_str.replace('''', "''', "', '")
    tweets_str = tweets_str.replace('''", ''''', "', '")
    tweets_str = tweets_str.replace('''", "''', "', '")
    tweet_list = tweets_str.split("', '")

    for tweet in tweet_list:
        tweet_p = my_preprocess(tweet)
        output_txt = output_txt + ' ' + tweet_p[0]
        if tweet_p[1] != []:
            output_emoji = output_emoji + ' ' + ' '.join(tweet_p[1])
        if tweet_p[2] != []:
            output_hash = output_hash + ' ' + ' '.join(tweet_p[2])
        if tweet_p[3] != []:
            output_mention = output_mention + ' ' + ' '.join(tweet_p[3])

    df_out.loc[0, 'user_id'] = user_id
    df_out.astype({'user_id': np.int32})
    df_out.loc[0, 'text'] = output_txt
    df_out.loc[0, 'emojis'] = output_emoji
    df_out.loc[0, 'hashtags'] = output_hash
    df_out.loc[0, 'mentions'] = output_mention

    return df_out


def tweet_split_2_process_v2(user_id, time, tweets_str):
    '''['podcast', 'time', 'text', 'emojis', 'hashtags', 'mentions']
    '''
    df_out = pd.DataFrame(columns=['podcast'])
    output_txt = ''
    output_emoji = ''
    output_hash = ''
    output_mention = ''

    tweets_str = tweets_str.replace('''', "''', "', '")
    tweets_str = tweets_str.replace('''", ''''', "', '")
    tweets_str = tweets_str.replace('''", "''', "', '")
    tweet_list = tweets_str.split("', '")

    for tweet in tweet_list:
        tweet_p = my_preprocess(tweet)
        output_txt = output_txt + ' ' + tweet_p[0]
        if tweet_p[1] != []:
            output_emoji = output_emoji + ' ' + ' '.join(tweet_p[1])
        if tweet_p[2] != []:
            output_hash = output_hash + ' ' + ' '.join(tweet_p[2])
        if tweet_p[3] != []:
            output_mention = output_mention + ' ' + ' '.join(tweet_p[3])

    df_out.loc[0, 'podcast'] = user_id
    df_out.loc[0, 'time'] = time
    df_out.loc[0, 'text'] = output_txt
    df_out.loc[0, 'emojis'] = output_emoji
    df_out.loc[0, 'hashtags'] = output_hash
    df_out.loc[0, 'mentions'] = output_mention

    return df_out


def my_preprocess(text):
    '''
    '''
    doc_emoji = find_emoji(text)
    doc_hash = find_hash(text)
    doc_mentions = find_mention(text)
    text = text.lower()
    text = text.replace('\\n',' ')
    text = p.clean(text)
    text = text.translate(str.maketrans(' ', ' ', punct_str))
    text = re.sub(r' \d+ ', ' ', text)
    text = re.sub(r' \d+ ', ' ', text)
    words = []
    for word in text.split(' '):
        words.append(word)
    words = [w for w in words if not w in stop_words]
    result = []
#     for token in gensim.utils.simple_preprocess(text):
#         if token not in stop_words:  # and len(token) > 3:
#             result.append(token)     # lemmatize_stemming(token))
#     result = result + doc_emoji + doc_hash + doc_mentions
    result = words + doc_emoji + doc_hash + doc_mentions
    tweet_txt = ' '.join(result)
#     return tweet_txt
    return ' '.join(words), doc_emoji, doc_hash, doc_mentions


X = os.listdir('/run/media/ed/SD/follower_tweets/')
X = sorted(X)
X

for pdcst in X[129:]:
    print('Converting {}...'.format(pdcst[:-4]), end='')
    pdcst_tweet_df = pd.read_csv('/run/media/ed/SD/follower_tweets/' + pdcst)
    tweet_split_df = pd.DataFrame(columns=['user_id', 'text', 'emojis', 'hashtags', 'mentions'])
    for x in range(len(pdcst_tweet_df)):
        if pdcst_tweet_df.loc[x, 'tweets'] != '[]':
            temp_df = tweet_split_2_process(pdcst_tweet_df.loc[x, 'user_id'], pdcst_tweet_df.loc[x, 'tweets'])
            tweet_split_df = tweet_split_df.append(temp_df, ignore_index=True)
    tweet_split_df['podcast_name'] = pdcst[:-4]
    print('Saving...', end='')
    tweet_split_df.to_pickle('/run/media/ed/SD/follower_tweets/' + pdcst[:-4] + '.pkl')
    print('Done')
